trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
      displayName: 'Use Python 3.10'
    - task: CmdLine@2
      displayName: 'Install tools'
      inputs:
        script: python -m pip install --upgrade pip setuptools wheel
    - task: CmdLine@2
      displayName: 'Install requirements'
      inputs:
        script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - task: CmdLine@2
      displayName: 'py-BOP-test'
      inputs:
        script: |
          #!/usr/bin/env python3
          # coding: utf-8
          $ ./SharePoint_Connection_Data_Processing.py

          



